version: 2
jobs:
  build:
    working_directory: ~/tmp
    
    docker:
        - image: circleci/python:3.6.1

    steps:
        - checkout

        - restore_cache:
            keys:
                - v1-dependencies-{{ checksum "requirements.txt" }}
                - v1-dependencies-

        - run:
            name: Virtualenv creating and deps install 
            command: |
                python3 -m virtualenv test_env
                . test_env/bin/activate
                pip install -r requirements.txt

        - save_cache:
            paths:
              - ./test_env
            key: v1-dependencies-{{ checksum "requirements.txt" }}
        - run:
            name: Create html page and store it as artifact
            command: |
                . test_env/bin/activate
                mkdir html-artifact
                jupyter nbconvert --execute 01/01_zaborovskiy.ipynb
                mv 01/01_zaborovskiy.html html-artifact/hw1.html
        - store_artifacts:
           path: html-artifact
           destination: html-artifact

